In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv("weather_data HCM 2c.csv")
df.head()

humidity  Rain
0        86     0
1        88     0
2        85     0
3        64     0
4        53     0

In [5]:
x, y = np.array(df["humidity"]).reshape((-1,1)),np.array(df["Rain"])
#  kiểm tra thông tin chuỗi x,y
print(x)
print(y)

[[86]
 [88]
 [85]
 [64]
 [53]
 [57]
 [77]
 [79]
 [84]
 [85]
 [80]
 [62]
 [53]
 [59]
 [76]
 [77]
 [84]
 [85]
 [83]
 [64]
 [49]
 [51]
 [70]
 [73]
 [75]
 [78]
 [76]
 [62]
 [53]
 [60]
 [77]
 [85]
 [88]
 [88]
 [87]
 [66]
 [51]
 [54]
 [73]
 [75]
 [77]
 [80]
 [78]
 [60]
 [50]
 [57]
 [77]
 [78]
 [81]
 [84]
 [80]
 [60]
 [53]
 [57]
 [71]
 [74]
 [76]
 [79]
 [78]
 [58]
 [49]
 [54]
 [73]
 [76]
 [78]
 [80]
 [79]
 [61]
 [48]
 [50]
 [71]
 [78]
 [80]
 [81]
 [81]
 [63]
 [51]
 [58]
 [74]
 [77]
 [80]
 [79]
 [82]
 [68]
 [60]
 [65]
 [81]
 [83]
 [87]
 [89]
 [85]
 [70]
 [61]
 [58]
 [72]
 [76]
 [83]
 [89]
 [88]
 [68]
 [50]
 [50]
 [66]
 [71]
 [77]
 [82]
 [84]
 [67]
 [56]
 [63]
 [84]
 [87]
 [88]
 [89]
 [92]
 [76]
 [63]
 [78]
 [89]
 [90]
 [90]
 [89]
 [87]
 [71]
 [67]
 [70]
 [81]
 [82]
 [83]
 [86]
 [85]
 [66]
 [50]
 [50]
 [70]
 [68]
 [73]
 [79]
 [77]
 [60]
 [46]
 [54]
 [63]
 [74]
 [72]
 [74]
 [70]
 [58]
 [47]
 [55]
 [71]
 [71]
 [74]
 [76]
 [77]
 [63]
 [47]
 [56]
 [75]
 [77]
 [81]
 [83]
 [81]
 [65]
 [54]
 [57]
 [79

In [6]:
model = LogisticRegression(solver="liblinear", C=10.0, random_state = 0)
model.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

lấy giá trị B0

In [7]:
model.intercept_

array([-4.12166578])

Lấy giá trị B1

In [8]:
model.coef_

array([[0.0297774]])